schema {
    query:Query
}   

type Query{
    me:Me
    login(username:String!,password:String!,code:String):Boolean
    credentialRequestOptions(username:String!):String
    loginWebAuthn(username:String!,assertion:String!):Boolean
}

type Me{
    user_id:Int
    username:String
    first_name:String
    last_name:String
    group:[UserGroup]
}

type UserGroup{
    name:String
}

